### ISSUE TITLE
Unexpected None causes crash

### ISSUE THREAD

**Issue by petermr** [petermr/pygetpapers#13]
```
pygetpapers -q "thymol and cyprus" -x -o test1
INFO: Total Hits are 77
INFO: Total Hits are 77
WARNING: Could not find more papers
Traceback (most recent call last):
  File "/opt/anaconda3/bin/pygetpapers", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.8/site-packages/pygetpapers/pygetpapers.py", line 655, in main
    callpygetpapers.handlecli()
  File "/opt/anaconda3/lib/python3.8/site-packages/pygetpapers/pygetpapers.py", line 634, in handlecli
    self.apipaperdownload(args.query, args.limit,
  File "/opt/anaconda3/lib/python3.8/site-packages/pygetpapers/pygetpapers.py", line 452, in apipaperdownload
    self.makecsv(query_result, makecsv=makecsv, makehtml=makehtml)
  File "/opt/anaconda3/lib/python3.8/site-packages/pygetpapers/pygetpapers.py", line 59, in makecsv
    for paper_number, papers in enumerate(searchvariable):
TypeError: 'NoneType' object is not iterable
```

**Comment by ayush4921** [comment]
Fixed in the latest commit.

Now output is something like:
`D:\main_projects\repositories>pygetpapers -q "thymol and cyprus" -x -o test1
INFO: Total Hits are 77
WARNING: pmcid field not found so paper was ignored
WARNING: pmcid field not found so paper was ignored
WARNING: Could not find more papers
WARNING: Keywords not found for paper 2
WARNING: html url not found for paper 8
WARNING: pdf url not found for paper 8
WARNING: Keywords not found for paper 10
WARNING: html url not found for paper 17
WARNING: pdf url not found for paper 17
WARNING: html url not found for paper 26
WARNING: pdf url not found for paper 26
WARNING: Author list not found for paper 27
WARNING: Keywords not found for paper 28
WARNING: Keywords not found for paper 31
WARNING: Keywords not found for paper 32
WARNING: Author list not found for paper 33
WARNING: Author list not found for paper 34
WARNING: html url not found for paper 36
WARNING: pdf url not found for paper 36
WARNING: Author list not found for paper 41`
